# Generated by Django 5.0 on 2023-12-22 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('df6a05e1-39bb-4fac-a6e1-3e8cb7a24c2f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6bca0be7-4c92-407b-bb7f-65c49506bc03'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ac5be46-e94d-4ae3-be31-c72a56923997'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
