# Generated by Django 5.0 on 2023-12-22 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2832e3f-20d8-49cc-ad1b-afa60befc658'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d36041e5-3e3f-4eca-aec7-30ca9ffc9b27'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('534d815d-50dc-4097-abfa-6e654a3f72e0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
