# Generated by Django 5.0 on 2023-12-22 21:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86b361be-5208-424a-ae2e-789b08c2108a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa722ee5-f860-4a0e-8f39-1a300fd9197b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('428fd936-0a36-489d-9985-0728f2e09bd8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
