# Generated by Django 5.0 on 2023-12-24 00:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a373e5a-1c2b-40d7-be0c-e2d1528bb42b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bb24a7a-cfbf-4695-a885-4678bd162b72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3938f5fa-a1b2-4cc6-9458-9fc95fd57070'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
