# Generated by Django 5.0 on 2023-12-24 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40a5efa1-ada9-4a66-a7a8-0f784961f290'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8195e30f-c229-4898-a4b6-208f774830f2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('663216b1-9acb-437a-9984-f1979c1d714b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
