# Generated by Django 5.0 on 2023-12-24 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bdbb153-07da-45bd-97f9-87701bb835af'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c4b1e72-ee5d-4e84-846d-cc52f96d5ccc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5202ef3-d330-447a-ac35-123841a9e1a8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
