# Generated by Django 5.0 on 2023-12-25 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_featured_image_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0948d92d-d268-419b-9f41-6e6eaba24e7e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b773022d-700a-4f4d-a0fc-59cdb3056f82'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('daa01de6-b724-477e-b5c5-ad868cd5c02a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
