# Generated by Django 5.0 on 2023-12-26 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_owner_alter_project_id_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6d7f26b-f8ec-4c16-ba79-70513ca12dfe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('679fed75-6894-4932-ac3d-7a53800f1da8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e01057d2-5457-4f52-af58-3ea87edc58a0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
