# Generated by Django 5.0 on 2023-12-30 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60d0cfb4-82b6-4ab9-8dfe-32c305835213'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc032b07-66ff-4d5a-b251-c6027ed3266d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14dc7610-7af9-4eb5-9b77-0bcb7fa6da9e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
