# Generated by Django 5.0 on 2024-01-02 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a07f36f-399b-4879-a4c0-1b96694ce9c1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c78d9ab-dd2f-4988-bc4d-1eab36c8f77d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7fef6059-bbe9-46e0-8d5b-fde5ed880c5d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
