# Generated by Django 5.0 on 2024-01-15 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99f2bafe-a910-463f-808e-cf318a3c1b42'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60a3bc61-1a18-415c-b6ae-70c3b8a982c5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de9ba3be-df23-41a8-b0e4-752355f9ea22'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
