# Generated by Django 5.0 on 2024-01-15 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3dcc8777-825f-496d-82f8-658cfe6ce42f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('16b831cc-652f-4e4d-9ee5-c40501cdec9c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('469f449a-ec12-4a23-b07e-a328d4de731d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
