# Generated by Django 5.0 on 2024-01-15 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_id_alter_review_id_alter_tag_id'),
        ('users', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6ca3008-9cb8-470f-9efa-7407d5b5a254'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f8dada7-a318-4744-832a-05e7f9e68810'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d6386b5-5fac-4d72-8e8e-c0c7b93e13fd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
